Algoritmo "sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : kaua oraboni
// Data atual  : 15/03/2024
Var
// Seção de Declarações das variáveis 
numero,sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite um numero")
leia(numero)
sucessor<- numero+1
escreval("resultado",sucessor)

Fimalgoritmo